<?php

/**
 * @file
 *  Provides site API key settings.
 */

/*
 * Implements hook_menu().
 */
function custom_module_menu() {
  $items['page_json/%/%node'] = array(
    'title' => 'JSON Node',
    'description' => 'Returns node in JSON form.',
    'page callback' => 'api_key_node',
    'page arguments' => array(1, 2),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Function to display JSON data on custom URL.
 */
function api_key_node($key, $node) {
  return drupal_json_output($node);
}

/**
 * Implements hook_form_alter().
 */
function custom_module_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $form['custom_module'] = array(
      '#type' => 'fieldset',
      '#title' => t('Site API Key'),
    );

    $form['custom_module']['siteapikey'] = array(
      '#type' => 'textfield',
      '#title' => t('API Key'),
      '#default_value' => variable_get('siteapikey'),
      '#attributes' => array(
        'placeholder' => t('No API Key yet'),
      ),
      '#description' => t('API key for your website.'),
    );

    $form['actions']['submit']['#value'] = t('Update Configuration');
    $form['#submit'][] = 'custom_module_submit';
  }
}

/**
 * Additional handler for site information settings form submit.
 */
function custom_module_submit($form, &$form_state) {
  $api_key = $form_state['values']['siteapikey'];
  variable_set('siteapikey', $api_key);
}
